let first = document.getElementById("first");
let a = first.getAttribute('class');
console.log(a);
console.log(first.hasAttribute('class'));
console.log(first.hasAttribute('style'));
// first.setAttribute("hidden","true");
// first.setAttribute("class","true rakib");
first.removeAttribute("class");
console.log(first.attributes);
console.log(first.attributes[0].value);
console.log(first.dataset);